/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/jupiter.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/jupiter.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cubemap.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/jupiter.glb')
