/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/saturn.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/saturn.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Saturn001.geometry} material={materials.None} />
      <mesh geometry={nodes.RingsTop.geometry} material={materials.SaturnRings} />
      <mesh geometry={nodes.RingsBottom.geometry} material={materials.SaturnRings} />
    </group>
  )
}

useGLTF.preload('/saturn.glb')
