/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/venus.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/venus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cylindrically_mapped_sphereMesh.geometry} material={materials['Default OBJ']} />
    </group>
  )
}

useGLTF.preload('/venus.glb')
